### ISSUE TITLE
Matching step 2

### ISSUE THREAD

**Issue by mickahell** [ESNFranceG33kTeam/sf_buddysystem#15]
Salut Jerem, 
Depuis... là maintenant tout de suite impossible pour moi de faire de matching,
En effet, quand je clic sur un EI dans la liste des matching, je suis redirigé sur une page qui n'existe/ne fonctionne pas. 
<img width="1123" alt="capture d ecran 2016-08-31 a 20 40 03" src="https://cloud.githubusercontent.com/assets/20951376/18152391/1e61e97e-6fbb-11e6-947e-f6102a134780.png">

**Comment by JeremieSamson** [comment]
C'est par rapport à tes dates de début de semestre (va vraiment falloir que jlenlève) remet à 01/09 et ton problème sera réglé. 
Si tu veux prendre en comptes les gens avant la date, change l'intervalle ;)
