### ISSUE TITLE
Dématching 

### ISSUE THREAD

**Issue by mickahell** [ESNFranceG33kTeam/sf_buddysystem#19]
Salut Jerem :)
J'ai un petit souci, tous mes matching depuis juillet 2016 ont été supprimé. En effet : 
- il semble que tous les EI inscrits depuis cette date soient réapparus dans ma liste de matching actuelle
- en vérifiant rapidement un ou 2 mentor, les buddy que je leurs ai affecté lors du 1er semestre n'apparaissent plus dans leur liste de buddies sur leur profil. 

J'avais pensé les réarchiver, mais cela va désactiver le compte de ceux ayant réactiver leur compte pour le 2nd semestre.

**Comment by JeremieSamson** [comment]
J'ai remis à jours les IS qui n'étaient pas archivé, est-ce mieux de ton côté ?

**Comment by g33kteam** [comment]
Nope, j'en ai toujours autant

*-- -- -- -- -- *
Mica Rollin - ESN InsiDijon
*Chair de la G33kTeam*
g33kteam@ixesn.fr
0676060243
Skype : mic_mic89700
——
G33K TEAM

 <https://www.facebook.com/MickahellMexicanos>
<https://twitter.com/mickahell89700>

****************************************************
Soyez écolo, n'imprimez que si nécessaire!


2017-01-09 14:29 GMT+01:00 Jérémie Samson <notifications@github.com>:

**Comment by g33kteam** [comment]
Nope, j'en ai toujours autant ca n'a rien changé

*-- -- -- -- -- *
Mica Rollin - ESN InsiDijon
*Chair de la G33kTeam*
g33kteam@ixesn.fr
0676060243
Skype : mic_mic89700
——
G33K TEAM

 <https://www.facebook.com/MickahellMexicanos>
<https://twitter.com/mickahell89700>

****************************************************
Soyez écolo, n'imprimez que si nécessaire!


2017-01-09 14:29 GMT+01:00 Jérémie Samson <notifications@github.com>:

**Comment by JeremieSamson** [comment]
Je suis passé de 96 à 54 users avec le dernier commit dans ta liste de matching, ça me parait proche de la réalité. On voit bien les utilisateurs du S1 restant 2 semestres n'ayant pas été matché et les nouveaux étudiants internationaux. J'ai rajouté une colonne

**Comment by mickahell** [comment]
Il m'a dematché tous buddies depuis le 2nd semestre (janvier 2016) de l'année dernière à tous les utilisateurs qui ont réactivé leur compte ce semestre ci. Après ils ne sont pas dans la liste des matching donc peut importe pour l'utilisation du BS ca ne pose pas de problème. 

Par contre dans ma liste des matching est toujours présent les buddies du S1, mais vu le nombre je pense qu'il ne s'agit que des buddies des utilisateurs qui ont réactivé leur compte ce semestre.

**Comment by JeremieSamson** [comment]
Ouep, je n'ai pas de suppression de compte donc je ne vois pas de cascade
possible sur les buddies associé, il va falloir que j'étudie ça de plus
prêt.

**Comment by mickahell** [comment]
Salut Jerem :)
T'en es où ? T'as réussi à faire quelque chose ? 
Moi c'est toujours pareil sur ma plateforme

**Comment by JeremieSamson** [comment]
Non, il faudra archiver les parrains restant à la main je ne peux pas être plus précis sans archiver des étudiants inscrit pour le S2 :/

**Comment by mickahell** [comment]
Dac, pas de problème j'attendrai la fin du semestre et j'archiverai tout le monde en même temps

**Comment by mickahell** [comment]
Je te laisse fermer cette issue du coup
