### ISSUE TITLE
Problème "no mail no cry"

### ISSUE THREAD

**Issue by mickahell** [ESNFranceG33kTeam/sf_buddysystem#25]
Salut Jérem :)
Tu vas bien ? 
J'ai un problème depuis quelques temps, en effet beaucoup d'utilisateur EI et mentor ne reçoivent pas/plus les mails que ce soit celui de réactivation ou celui de matching. 

Jérem de Compi m'a rapporté hier avoir le même problème.

**Comment by JeremieSamson** [comment]
Le mail de réactivation a en effet eu des soucis, l'utilisateur peut maintenant réactiver son compte en se connectant avec et en cliquant sur un simple lien, il ne peut pas le louper c'est sur le dashboard. 
Pour les mails de matching, je viens de faire le test et j'ai bien l'email correspondant je ne vois donc pas de problème avec l'email au sein de l'application ?

**Comment by mickahell** [comment]
Ouais on voit bien les mails, mais quand j'ai fait les matching, beaucoup ne recevaient pas les mails et ils ne sont mêem pas en spam

**Comment by JeremieSamson** [comment]
J'ai testé de mon côté et ça fonctionne belle et bien, est-ce quelque chose de systématique ou ça arrive plutot de temps en temps ?

**Comment by mickahell** [comment]
Ca m'est souvent arrivé quand je faisais les matching et je sais que ca le faisait aussi à Jerem (de Compi)

**Comment by mickahell** [comment]
Salut Jerem :)
J'ai des news là dessus, ca vient de me réarriver aujourd'hui. J'ai fait 2 matchs, et les 2 mentors m'ont dit ne jamais avoir recu de mails
