### ISSUE TITLE
Problème matching plusieurs EI 

### ISSUE THREAD

**Issue by Leajarland** [ESNFranceG33kTeam/sf_buddysystem#27]
Les étudiants locaux peuvent parrainer 2 EI mais souvent après les avoir matchés à un EI une première fois, ils disparaissent de la liste donc il est impossible de les matchés une seconde fois

**Comment by Leajarland** [comment]
Les étudiants locaux ne contactent pas forcément les internationaux et dans ce cas, la section les archive mais impossible par la suite de rematcher un EI avec une autre personne

**Comment by mickahell** [comment]
Le fait qu'ils disparaissent dépend des paramètres dans l'onglet section.  

Il faut les démartcher avant

**Comment by Leajarland** [comment]
Ok merci je vais transmettre cette info aux sections concernées :)

**Comment by JeremieSamson** [comment]
Je pense que ce problème est réglé depuis la 2.5.1 ?
