### ISSUE TITLE
Problème mailing list ou liste d'étudiants locaux

### ISSUE THREAD

**Issue by Leajarland** [ESNFranceG33kTeam/sf_buddysystem#28]
Certains étudiants locaux sont déjà parrains/marraines et on les retrouve malgré tout dans la liste des demandeurs

**Comment by mickahell** [comment]
Tous dépend des paramètres dans l'onglet section

**Comment by Leajarland** [comment]
Merci pour ta réponse

**Comment by JeremieSamson** [comment]
Egalement réglé avec la 2.5.1, si oui, fermer le ticket
