### ISSUE TITLE
Connexion Problem

### ISSUE THREAD

**Issue by mickahell** [ESNFranceG33kTeam/sf_buddysystem#6]
Un utilisateur (français) m'a rapporté qui lui est impossible de se connecter.
-Il utilise la connexion par Facebook
-Il n'a aucun message d'erreur

**Comment by JeremieSamson** [comment]
Pourrais-tu m'envoyer son email par email stp, la connexion en elle même fonctionne, ça doit être lié à son compte.

**Comment by mickahell** [comment]
Yop: alexandre_s@hotmail.fr

**Comment by JeremieSamson** [comment]
Il est en effet inscrit avec cette adresse, il utilise bien cette adresse sur son facebook ?si c'est un email différent c'est normal que ça ne fonctionne pas.

**Comment by mickahell** [comment]
Ouep, c’est bien celle ci qu’il utilise sur Facebook
