### ISSUE TITLE
User problem

### ISSUE THREAD

**Issue by mickahell** [ESNFranceG33kTeam/sf_buddysystem#7]
Salut Jérem :)
J'ai un problème au niveau des utilisateurs depuis quelques jours, 
En effet j'ai des utilisateurs que je ne trouve plus dans ma liste de matching.
C'est plus précisément nous autres les ESN, le seul point commun que je vois est ce que tous ces utilisateurs sont inscrits depuis l'année dernière (s2 - 2015).

Sachant que je leur ai déjà attribué un buddy il y a quelques temps et que ma limite de buddy par parrain est de ... beaucoup.

**Comment by JeremieSamson** [comment]
Je pense avoir réglé le problème, tu peux me dire si c'est toujours en cours ?

**Comment by mickahell** [comment]
Nouveaux problème àa ce niveau depuis la maintenant :
- J'ai supprimé 2 utilisateurs et quand j'ai été faire du matching je les ai revu dans la liste. 
- Ma liste de matching ne comprend que 7 utilisateurs maintenant (ceux qui n'ont aucun Buddy)
