### ISSUE TITLE
Mail problem

### ISSUE THREAD

**Issue by mickahell** [ESNFranceG33kTeam/sf_buddysystem#8]
Salut Jerem,
Quand je modifie les modèles de l'email dans la section Emails lists, 
Il ne se modifie pas dans les mails au moment du matching.

**Comment by JeremieSamson** [comment]
J'ai rajouté un fix, pareil tu peux checker de ton côté ?

**Comment by mickahell** [comment]
Pour le mail c’est bon et pour les utilisateur aussi je peux voir ce que je cherchais l’autre coup.


Gracias Jerem :D
